### ISSUE TITLE
Issue an update (a new release) with important bug fixes

### ISSUE THREAD

**Issue by ddobrev** [RowenStipe/qTox-OSX#6]
@tux3 has just committed code that resolves multiple problems, including a crash (https://github.com/tux3/qTox/issues/2840). Please upload an update and a new DMG in order to include those fixes.

**Comment by ddobrev** [comment]
In more general, may I suggest https://travis-ci.org/ as a build server? It offers remote (that is, you don't have to install locally on your own mac) OS X builds and it has GitHub integration. We use it for https://github.com/mono/CppSharp.

**Comment by RowenStipe** [comment]
Travis is great for testing builds but not actually compiling and deploying an application for OS X. I just got back to my computer so give me a few hours and I'll have a new release put out.

The entirety of the code section is  mainly just because I felt like the contents of the DMG + Extras should exist there.

**Comment by RowenStipe** [comment]
Update is live! https://github.com/RowenStipe/qTox-OSX/releases/tag/1.2.4.307

**Comment by ddobrev** [comment]
@RowenStipe thank you very much. qTox crashed silently quite a few times on OS X, most probably precisely because of the numerous spawned threads as explained in the mentioned issue. With them fixed, the client should be stable now.

**Comment by ddobrev** [comment]
@RowenStipe one last thing, did you create the update from master or stable of qTox? The fixes I have in mind have so far only been merged to master.
